height: 500
menubar: true
toolbar:
  - undo redo | styles | bold italic underline | backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | table | help
plugins:
  - advlist autolink lists link image charmap preview anchor searchreplace visualblocks fullscreen insertdatetime media table code help wordcount
language: ru
promotion: false
style_formats_merge: true
